---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneRole
metadata:
  name: edpm-role-0
spec:
  nodeTemplate:
    extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-conf-files
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
    ansibleUser: root
    ansiblePort: 22
    managementNetwork: ctlplane
    networkConfig:
      template: templates/net_config_bridge.j2
    managed: false
    ansibleVars: |
      edpm_network_config_template: templates/net_config_bridge.j2
      edpm_network_config_hide_sensitive_logs: false
      neutron_physical_bridge_name: br-ex
      neutron_public_interface_name: eth0
      ctlplane_dns_nameservers:
      - 192.168.122.1
      dns_search_domains: []
      tenant_ip: 192.168.24.100
      edpm_ovn_dbs: 192.168.24.1
      edpm_ceph_client_files_source: /etc/ceph
      edpm_ceph_client_files_config_home: /etc/ceph
