apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./core_v1beta1_openstackcontrolplane.yaml
namespace: openstack
patches:
- patch: |-
    - op: replace
      path: /spec/secret
      value: osp-secret
    - op: replace
      path: /spec/storageClass
      value: "local-storage"
    - op: replace
      path: /spec/cinder/template/cinderBackup/replicas
      value: 0
    - op: add
      path: /spec/extraMounts
      value:
        - name: v1
          region: r1
          extraVol:
          - propagation:
            - Glance
            - volume1
            - CinderBackup
            extraVolType: Ceph
            volumes:
            - name: ceph
              projected:
                sources:
                - secret:
                    name: ceph-client-conf
            mounts:
            - name: ceph
              mountPath: "/etc/ceph"
              readOnly: true
    - op: add
      path: /spec/cinder/template/cinderVolumes/volume1/customServiceConfig
      value: |
            [DEFAULT]
            enabled_backends=ceph
            [ceph]
            volume_backend_name=ceph
            volume_driver=cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf=/etc/ceph/ceph.conf
            rbd_user=openstack
            rbd_pool=volumes
            rbd_flatten_volume_from_snapshot=False
            report_discard_supported=True
            backend_host=hostgroup
            rbd_secret_uuid=FSID
    - op: add
      path: /spec/cinder/template/cinderBackup/customServiceConfig
      value: |
            [DEFAULT]
            backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
            backup_ceph_pool = backups
            backup_ceph_user = openstack
    - op: add
      path: /spec/glance/template/customServiceConfig
      value: |
            [DEFAULT]
            debug = true
            enabled_backends=default_backend:rbd
            [glance_store]
            default_backend=default_backend
            [default_backend]
            rbd_store_ceph_conf=/etc/ceph/ceph.conf
            rbd_store_user=openstack
            rbd_store_pool=images
            store_description=ceph_glance_store
  target:
    kind: OpenStackControlPlane
