apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-configmap
  namespace: openstack
data:
  inventory.yaml: |
    allovercloud:
      children:
        overcloud:
            children:
              Compute:
                hosts:
                  192.168.122.X:
                    ansible_ssh_user: root
                    ctlplane_ip: 192.168.24.100
                    internal_api_ip: 192.168.24.2
                    tenant_ip: 192.168.24.2
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                  192.168.122.Y:
                    ansible_ssh_user: root
                    ctlplane_ip: 192.168.24.101
                    internal_api_ip: 192.168.24.3
                    tenant_ip: 192.168.24.3
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                  192.168.122.Z:
                    ansible_ssh_user: root
                    ctlplane_ip: 192.168.24.102
                    internal_api_ip: 192.168.24.4
                    tenant_ip: 192.168.24.4
                    fqdn_internal_api: '{{ ansible_fqdn }}'
                vars:
                  chrony_ntp_servers:
                    - clock.redhat.com
                    - clock2.redhat.com
          
