apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: verify-ansible
  namespace: openstack
spec:
  image: "quay.io/tripleomastercentos9/openstack-tripleo-ansible-ee:current-tripleo"
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
  extraMounts:
    - volumes:
        - name: inventory
          configMap:
            name: inventory-configmap
        - name: ssh-key
          secret:
            secretName: ansibleee-ssh-key-secret
            items:
              - key: private_ssh_key
                path: ssh_key
      mounts:
        - name: inventory
          mountPath: /runner/inventory/inventory.yaml
          subPath: inventory.yaml          
        - name: ssh-key
          mountPath: /runner/env/ssh_key
          subPath: ssh_key
  play: |
    - hosts: all
      gather_facts: false
      vars:
        cmd: "uname -a"
      tasks:
        - name: run command
          shell: "{{ cmd }}"
          register: cmd_out
        - name: show command output
          debug:
            msg: "{{ cmd_out.stdout }}"
